import type {ComponentRegistry} from "./types";

export const componentRegistry: ComponentRegistry = [
    {
        slug: "button",
        sourceFile: "components/ui/button.tsx",
        category: "form",
        name: {en: "Button", fa: "دکمه"},
        description: {
            en: "A flexible action button with consistent variants, sizes, and focus states.",
            fa: "دکمه‌ای منعطف با واریانت‌ها، اندازه‌ها و حالت‌های فوکوس یکپارچه.",
        },
        props: [
            {name: "variant", type: '"primary" | "secondary" | "form"', required: false, defaultValue: '"primary"', description: {en: "Visual button style.", fa: "سبک ظاهری دکمه."}},
            {name: "size", type: '"sm" | "md" | "lg"', required: false, defaultValue: '"md"', description: {en: "Button size.", fa: "اندازه دکمه."}},
            {name: "radius", type: '"default" | "full"', required: false, defaultValue: '"default"', description: {en: "Corner radius.", fa: "گردی گوشه‌ها."}},
            {name: "type", type: '"button" | "submit" | "reset"', required: false, defaultValue: '"button"', description: {en: "Native button type.", fa: "نوع استاندارد دکمه در HTML."}},
            {name: "disabled", type: "boolean", required: false, defaultValue: "false", description: {en: "Disables interaction with the button.", fa: "تعامل با دکمه را غیرفعال می‌کند."}},
            {name: "className", type: "string", required: false, description: {en: "Additional CSS classes.", fa: "کلاس‌های CSS اضافی."}},
            {name: "children", type: "ReactNode", required: false, description: {en: "Button content.", fa: "محتوای دکمه."}},
        ],
        examples: [
            {title: {en: "Primary action", fa: "عمل اصلی"}, code: `<Button>Continue</Button>`},
            {title: {en: "Secondary action", fa: "عمل ثانویه"}, code: `<Button variant="secondary" size="sm">Cancel</Button>`},
            {title: {en: "Form submit", fa: "ارسال فرم"}, code: `<Button variant="form" type="submit">Send message</Button>`},
            {title: {en: "Full radius", fa: "گوشه کاملاً گرد"}, code: `<Button radius="full">Get started</Button>`},
        ],
    },
    {
        slug: "input",
        sourceFile: "components/ui/input.tsx",
        category: "form",
        name: {en: "Input", fa: "ورودی"},
        description: {
            en: "A reusable text input with consistent sizing, borders, and interaction states.",
            fa: "ورودی متنی قابل استفاده مجدد با اندازه، حاشیه و حالت‌های تعاملی یکپارچه.",
        },
        props: [
            {name: "type", type: "string", required: false, defaultValue: '"text"', description: {en: "Native HTML input type such as text, email, or password.", fa: "نوع استاندارد ورودی مانند text، email یا password."}},
            {name: "placeholder", type: "string", required: false, description: {en: "Placeholder text shown when the field is empty.", fa: "متن راهنما هنگام خالی بودن فیلد."}},
            {name: "name", type: "string", required: false, description: {en: "Form field name.", fa: "نام فیلد برای فرم."}},
            {name: "id", type: "string", required: false, description: {en: "Input id, useful for associating a FormField label.", fa: "شناسه ورودی، برای اتصال به برچسب FormField کاربرد دارد."}},
            {name: "value", type: "string | number | readonly string[]", required: false, description: {en: "Controlled input value.", fa: "مقدار کنترل‌شده ورودی."}},
            {name: "defaultValue", type: "string | number | readonly string[]", required: false, description: {en: "Initial uncontrolled value.", fa: "مقدار اولیه در حالت کنترل‌نشده."}},
            {name: "required", type: "boolean", required: false, defaultValue: "false", description: {en: "Marks the input as required for native form validation.", fa: "فیلد را برای اعتبارسنجی استاندارد فرم الزامی می‌کند."}},
            {name: "disabled", type: "boolean", required: false, defaultValue: "false", description: {en: "Disables the input.", fa: "ورودی را غیرفعال می‌کند."}},
            {name: "className", type: "string", required: false, description: {en: "Additional CSS classes.", fa: "کلاس‌های CSS اضافی."}},
        ],
        examples: [
            {title: {en: "Email input", fa: "ورودی ایمیل"}, code: `<Input type="email" name="email" placeholder="you@example.com" />`},
            {title: {en: "Required field", fa: "فیلد الزامی"}, code: `<Input id="email" type="email" required placeholder="Your email" />`},
            {title: {en: "Password input", fa: "ورودی رمز عبور"}, code: `<Input type="password" placeholder="Your password" />`},
            {title: {en: "Disabled state", fa: "حالت غیرفعال"}, code: `<Input placeholder="Unavailable" disabled />`},
        ],
    },
    {
        slug: "textarea",
        sourceFile: "components/ui/textarea.tsx",
        category: "form",
        name: {en: "Textarea", fa: "ناحیه متن"},
        description: {
            en: "A reusable multiline field for longer user input.",
            fa: "فیلد چندخطی قابل استفاده مجدد برای ورود متن‌های طولانی‌تر.",
        },
        props: [
            {name: "placeholder", type: "string", required: false, description: {en: "Placeholder text shown when the field is empty.", fa: "متن راهنما هنگام خالی بودن فیلد."}},
            {name: "rows", type: "number", required: false, description: {en: "Suggested visible text rows.", fa: "تعداد پیشنهادی ردیف‌های قابل مشاهده."}},
            {name: "name", type: "string", required: false, description: {en: "Form field name.", fa: "نام فیلد برای فرم."}},
            {name: "id", type: "string", required: false, description: {en: "Textarea id, useful for associating a FormField label.", fa: "شناسه textarea، برای اتصال به برچسب FormField کاربرد دارد."}},
            {name: "value", type: "string | number | readonly string[]", required: false, description: {en: "Controlled textarea value.", fa: "مقدار کنترل‌شده textarea."}},
            {name: "defaultValue", type: "string | number | readonly string[]", required: false, description: {en: "Initial uncontrolled value.", fa: "مقدار اولیه در حالت کنترل‌نشده."}},
            {name: "required", type: "boolean", required: false, defaultValue: "false", description: {en: "Marks the field as required for native form validation.", fa: "فیلد را برای اعتبارسنجی استاندارد فرم الزامی می‌کند."}},
            {name: "disabled", type: "boolean", required: false, defaultValue: "false", description: {en: "Disables the textarea.", fa: "textarea را غیرفعال می‌کند."}},
            {name: "className", type: "string", required: false, description: {en: "Additional CSS classes.", fa: "کلاس‌های CSS اضافی."}},
        ],
        examples: [
            {title: {en: "Message field", fa: "فیلد پیام"}, code: `<Textarea name="message" placeholder="Write a message..." rows={5} />`},
            {title: {en: "Required message", fa: "پیام الزامی"}, code: `<Textarea id="message" required rows={5} placeholder="Your message" />`},
            {title: {en: "Compact note", fa: "یادداشت کوتاه"}, code: `<Textarea rows={3} placeholder="Add a note..." />`},
        ],
    },
    {
        slug: "form-field",
        sourceFile: "components/ui/form-field.tsx",
        category: "form",
        name: {en: "Form Field", fa: "فیلد فرم"},
        description: {
            en: "A semantic label wrapper for consistent form field structure.",
            fa: "یک wrapper معنایی برای ساختار یکپارچه فیلدهای فرم.",
        },
        props: [
            {name: "label", type: "ReactNode", required: true, description: {en: "Visible field label.", fa: "برچسب قابل مشاهده فیلد."}},
            {name: "children", type: "ReactNode", required: true, description: {en: "Form control rendered below the label.", fa: "کنترل فرم که زیر برچسب نمایش داده می‌شود."}},
            {name: "htmlFor", type: "string", required: false, description: {en: "Id of the associated form control.", fa: "شناسه کنترل فرم مرتبط."}},
            {name: "className", type: "string", required: false, description: {en: "Additional CSS classes for the label.", fa: "کلاس‌های CSS اضافی برای برچسب."}},
        ],
        examples: [
            {title: {en: "Labeled email field", fa: "فیلد ایمیل دارای برچسب"}, code: `<FormField label="Email" htmlFor="email"><Input id="email" type="email" /></FormField>`},
            {title: {en: "Labeled message field", fa: "فیلد پیام دارای برچسب"}, code: `<FormField label="Message" htmlFor="message"><Textarea id="message" rows={5} /></FormField>`},
        ],
    },
    {
        slug: "divider",
        sourceFile: "components/ui/divider.tsx",
        category: "layout",
        name: {en: "Divider", fa: "جداکننده"},
        description: {
            en: "A lightweight visual separator with solid and directional gradient variants.",
            fa: "جداکننده‌ای سبک با حالت ساده و گرادیان جهت‌دار.",
        },
        props: [
            {name: "variant", type: '"solid" | "gradient"', required: false, defaultValue: '"solid"', description: {en: "Divider visual style.", fa: "سبک ظاهری جداکننده."}},
            {name: "direction", type: '"ltr" | "rtl"', required: false, defaultValue: '"ltr"', description: {en: "Gradient direction when using the gradient variant.", fa: "جهت گرادیان هنگام استفاده از حالت gradient."}},
            {name: "className", type: "string", required: false, description: {en: "Additional CSS classes.", fa: "کلاس‌های CSS اضافی."}},
        ],
        examples: [
            {title: {en: "Solid divider", fa: "جداکننده ساده"}, code: `<Divider />`},
            {title: {en: "Gradient divider", fa: "جداکننده گرادیانی"}, code: `<Divider variant="gradient" />`},
            {title: {en: "RTL gradient", fa: "گرادیان راست به چپ"}, code: `<Divider variant="gradient" direction="rtl" />`},
        ],
    },
    {
        slug: "badge",
        sourceFile: "components/ui/badge.tsx",
        category: "feedback",
        name: {en: "Badge", fa: "نشان"},
        description: {en: "Compact status and category label.", fa: "برچسب فشرده برای وضعیت و دسته‌بندی."},
        props: [
            {name: "variant", type: '"neutral" | "dark" | "accent"', required: false, defaultValue: '"neutral"', description: {en: "Badge visual style.", fa: "سبک ظاهری نشان."}},
            {name: "children", type: "ReactNode", required: false, description: {en: "Badge content.", fa: "محتوای نشان."}},
        ],
        examples: [{title: {en: "Neutral", fa: "خنثی"}, code: `<Badge>New</Badge>`}, {title: {en: "Accent", fa: "تاکیدی"}, code: `<Badge variant="accent">Coming soon</Badge>`}],
    },
    {
        slug: "card",
        sourceFile: "components/ui/card.tsx",
        category: "layout",
        name: {en: "Card", fa: "کارت"},
        description: {en: "A simple surface for grouping related content.", fa: "سطحی ساده برای گروه‌بندی محتوای مرتبط."},
        props: [
            {name: "interactive", type: "boolean", required: false, defaultValue: "false", description: {en: "Adds an interactive hover treatment.", fa: "حالت تعاملی هنگام hover را فعال می‌کند."}},
            {name: "children", type: "ReactNode", required: false, description: {en: "Card content.", fa: "محتوای کارت."}},
        ],
        examples: [{title: {en: "Basic card", fa: "کارت ساده"}, code: `<Card>Content</Card>`}],
    },
    {
        slug: "alert",
        sourceFile: "components/ui/alert.tsx",
        category: "feedback",
        name: {en: "Alert", fa: "هشدار"},
        description: {en: "Contextual feedback message for important status information.", fa: "پیام بازخوردی برای نمایش وضعیت یا اطلاعات مهم."},
        props: [
            {name: "variant", type: '"info" | "success" | "warning" | "danger"', required: false, defaultValue: '"info"', description: {en: "Alert tone.", fa: "نوع پیام هشدار."}},
            {name: "role", type: "string", required: false, defaultValue: '"status"', description: {en: "Accessibility role.", fa: "نقش دسترسی‌پذیری."}},
        ],
        examples: [{title: {en: "Success", fa: "موفقیت"}, code: `<Alert variant="success">Saved successfully.</Alert>`}],
    },
    {
        slug: "checkbox",
        sourceFile: "components/ui/checkbox.tsx",
        category: "form",
        name: {en: "Checkbox", fa: "چک‌باکس"},
        description: {en: "Native checkbox control with MinKits focus styling.", fa: "کنترل checkbox استاندارد با استایل فوکوس MinKits."},
        props: [{name: "checked", type: "boolean", required: false, description: {en: "Controlled checked state.", fa: "وضعیت کنترل‌شده انتخاب."}}, {name: "disabled", type: "boolean", required: false, description: {en: "Disables the control.", fa: "کنترل را غیرفعال می‌کند."}}],
        examples: [{title: {en: "Basic checkbox", fa: "چک‌باکس ساده"}, code: `<Checkbox aria-label="Accept terms" />`}],
    },
    {
        slug: "radio",
        sourceFile: "components/ui/radio.tsx",
        category: "form",
        name: {en: "Radio", fa: "رادیو"},
        description: {en: "Native radio control for mutually exclusive choices.", fa: "کنترل radio استاندارد برای انتخاب‌های متقابل."},
        props: [{name: "name", type: "string", required: true, description: {en: "Radio group name.", fa: "نام گروه رادیویی."}}, {name: "value", type: "string", required: false, description: {en: "Radio value.", fa: "مقدار گزینه."}}],
        examples: [{title: {en: "Choice", fa: "انتخاب"}, code: `<Radio name="plan" value="pro" aria-label="Pro" />`}],
    },
    {
        slug: "select",
        sourceFile: "components/ui/select.tsx",
        category: "form",
        name: {en: "Select", fa: "انتخاب‌گر"},
        description: {en: "Styled native select for compact option groups.", fa: "select استاندارد با استایل یکپارچه برای گروه گزینه‌ها."},
        props: [{name: "value", type: "string", required: false, description: {en: "Selected value.", fa: "مقدار انتخاب‌شده."}}, {name: "disabled", type: "boolean", required: false, description: {en: "Disables the select.", fa: "انتخاب‌گر را غیرفعال می‌کند."}}],
        examples: [{title: {en: "Basic select", fa: "انتخاب‌گر ساده"}, code: `<Select defaultValue="react"><option value="react">React</option><option value="next">Next.js</option></Select>`}],
    },
    {
        slug: "switch",
        sourceFile: "components/ui/switch.tsx",
        category: "form",
        name: {en: "Switch", fa: "سوئیچ"},
        description: {en: "Accessible boolean toggle with controlled and uncontrolled modes.", fa: "کلید دوحالته دسترس‌پذیر با حالت کنترل‌شده و کنترل‌نشده."},
        props: [{name: "checked", type: "boolean", required: false, description: {en: "Controlled state.", fa: "وضعیت کنترل‌شده."}}, {name: "defaultChecked", type: "boolean", required: false, defaultValue: "false", description: {en: "Initial uncontrolled state.", fa: "وضعیت اولیه کنترل‌نشده."}}, {name: "onCheckedChange", type: "(checked: boolean) => void", required: false, description: {en: "Called when the value changes.", fa: "هنگام تغییر مقدار اجرا می‌شود."}}],
        examples: [{title: {en: "Toggle", fa: "تغییر وضعیت"}, code: `<Switch aria-label="Enable notifications" />`}],
    },
    {
        slug: "tabs",
        sourceFile: "components/ui/tabs.tsx",
        category: "navigation",
        name: {en: "Tabs", fa: "تب‌ها"},
        description: {en: "Keyboard-friendly tabbed content container.", fa: "ظرف محتوای تب‌بندی‌شده با ساختار مناسب دسترسی‌پذیری."},
        props: [{name: "items", type: "readonly TabItem[]", required: true, description: {en: "Tab definitions and content.", fa: "تعریف تب‌ها و محتوای آن‌ها."}}, {name: "defaultValue", type: "string", required: false, description: {en: "Initially active tab id.", fa: "شناسه تب فعال اولیه."}}, {name: "ariaLabel", type: "string", required: false, defaultValue: '"Tabs"', description: {en: "Accessible tablist label.", fa: "برچسب دسترسی‌پذیر گروه تب‌ها."}}],
        examples: [{title: {en: "Two tabs", fa: "دو تب"}, code: `<Tabs items={[{id: "preview", label: "Preview", content: <div />}, {id: "code", label: "Code", content: <div /> }]} />`}],
    },
    {
        slug: "tooltip",
        sourceFile: "components/ui/tooltip.tsx",
        category: "navigation",
        name: {en: "Tooltip", fa: "راهنما"},
        description: {en: "Small contextual hint revealed on hover or focus.", fa: "راهنمای کوتاه که با hover یا focus نمایش داده می‌شود."},
        props: [{name: "content", type: "ReactNode", required: true, description: {en: "Tooltip content.", fa: "محتوای راهنما."}}, {name: "children", type: "ReactNode", required: true, description: {en: "Trigger element.", fa: "عنصر فعال‌کننده."}}],
        examples: [{title: {en: "Hint", fa: "راهنما"}, code: `<Tooltip content="More information"><Button aria-label="More information">?</Button></Tooltip>`}],
    },
    {
        slug: "modal",
        sourceFile: "components/ui/modal.tsx",
        category: "navigation",
        name: {en: "Modal", fa: "مودال"},
        description: {en: "Accessible dialog surface powered by Headless UI.", fa: "سطح گفت‌وگوی دسترس‌پذیر مبتنی بر Headless UI."},
        props: [{name: "open", type: "boolean", required: true, description: {en: "Whether the dialog is open.", fa: "آیا گفت‌وگو باز است یا نه."}}, {name: "onClose", type: "(open: boolean) => void", required: true, description: {en: "Called when the dialog closes.", fa: "هنگام بسته شدن گفت‌وگو اجرا می‌شود."}}, {name: "title", type: "ReactNode", required: false, description: {en: "Dialog title.", fa: "عنوان گفت‌وگو."}}],
        examples: [{title: {en: "Dialog", fa: "گفت‌وگو"}, code: `<Modal open={open} onClose={setOpen} title="Confirm">Content</Modal>`}],
    },
];
