import type {ComponentRegistryItem} from "./types";

const sourceBySlug: Record<string, string> = {
    button: "import type {ButtonHTMLAttributes} from \"react\";\n\ntype ButtonVariant = \"primary\" | \"secondary\" | \"form\";\ntype ButtonSize = \"sm\" | \"md\" | \"lg\";\ntype ButtonRadius = \"default\" | \"full\";\n\nexport type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {\n    variant?: ButtonVariant;\n    size?: ButtonSize;\n    radius?: ButtonRadius;\n};\n\nconst variants: Record<ButtonVariant, string> = {\n    primary: \"bg-button-primary text-white border border-button-primary hover:bg-button-primary-hover\",\n    secondary: \"bg-button-secondary text-button-text border border-button-text hover:bg-button-secondary-hover hover:text-white\",\n    form: \"border border-form-button-start bg-linear-to-r from-form-button-start to-form-button-end text-white hover:from-form-button-hover-start hover:to-form-button-hover-end\",\n};\n\nconst radiuses: Record<ButtonRadius, string> = {\n    default: \"rounded-xl\",\n    full: \"rounded-full\",\n};\n\nconst sizes: Record<ButtonSize, string> = {\n    sm: \"h-10 px-4 text-xs\",\n    md: \"h-12 px-6 text-sm\",\n    lg: \"h-14 px-8 text-base\",\n};\n\nexport default function Button({\n    variant = \"primary\",\n    size = \"md\",\n    radius = \"default\",\n    className = \"\",\n    type = \"button\",\n    children,\n    ...props\n}: ButtonProps) {\n    return (\n        <button\n            type={type}\n            className={[\n                \"inline-flex items-center justify-center font-semibold transition-colors duration-200\",\n                \"focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-button-focus\",\n                \"disabled:pointer-events-none disabled:opacity-50\",\n                variants[variant],\n                radiuses[radius],\n                sizes[size],\n                className,\n            ].filter(Boolean).join(\" \")}\n            {...props}\n        >\n            {children}\n        </button>\n    );\n}",
    input: "import type {InputHTMLAttributes} from \"react\";\n\nexport type InputProps = InputHTMLAttributes<HTMLInputElement>;\n\nexport default function Input({className = \"\", ...props}: InputProps) {\n    return (\n        <input\n            className={[\n                \"h-12 w-full min-w-0 rounded-xl border border-input-border bg-input-background px-4 text-sm text-input-text outline-none transition-colors\",\n                \"placeholder:text-input-placeholder focus:border-input-border-focus focus:ring-0\",\n                \"disabled:pointer-events-none disabled:opacity-50\",\n                className,\n            ].filter(Boolean).join(\" \")}\n            {...props}\n        />\n    );\n}",
    textarea: "import type {TextareaHTMLAttributes} from \"react\";\n\nexport type TextareaProps = TextareaHTMLAttributes<HTMLTextAreaElement>;\n\nexport default function Textarea({className = \"\", ...props}: TextareaProps) {\n    return (\n        <textarea\n            className={[\n                \"min-h-32 w-full min-w-0 resize-y rounded-xl border border-input-border bg-input-background px-4 py-3 text-sm text-input-text outline-none transition-colors\",\n                \"placeholder:text-input-placeholder focus:border-input-border-focus focus:ring-0\",\n                \"disabled:pointer-events-none disabled:opacity-50\",\n                className,\n            ].filter(Boolean).join(\" \")}\n            {...props}\n        />\n    );\n}",
    "form-field": "import type {LabelHTMLAttributes, ReactNode} from \"react\";\n\nexport type FormFieldProps = LabelHTMLAttributes<HTMLLabelElement> & {\n    label: ReactNode;\n    children: ReactNode;\n};\n\nexport default function FormField({\n    label,\n    children,\n    className = \"\",\n    htmlFor,\n    ...props\n}: FormFieldProps) {\n    return (\n        <div className=\"min-w-0\">\n            <label\n                htmlFor={htmlFor}\n                className={[\"mb-2 block text-sm text-form-label\", className].filter(Boolean).join(\" \")}\n                {...props}\n            >\n                {label}\n            </label>\n            {children}\n        </div>\n    );\n}",
    divider: "type DividerVariant = \"solid\" | \"gradient\";\ntype DividerDirection = \"ltr\" | \"rtl\";\n\ntype DividerProps = {\n    variant?: DividerVariant;\n    direction?: DividerDirection;\n    className?: string;\n};\n\nexport default function Divider({\n    variant = \"solid\",\n    direction = \"ltr\",\n    className = \"\",\n}: DividerProps) {\n    return (\n        <div\n            aria-hidden=\"true\"\n            className={[\n                \"h-px w-full\",\n                variant === \"solid\"\n                    ? \"bg-divider\"\n                    : [\n                        direction === \"rtl\" ? \"bg-linear-to-l\" : \"bg-linear-to-r\",\n                        \"from-divider-gradient-start via-divider-gradient-mid to-divider-gradient-end\",\n                    ].join(\" \"),\n                className,\n            ].filter(Boolean).join(\" \")}\n        />\n    );\n}",
};

export function getComponentSource(component: ComponentRegistryItem) {
    return sourceBySlug[component.slug] ?? "";
}
