import type { Lang } from "./config";

export type Messages = typeof messages.en;

export const messages = {
  en: {
    nav: { home: "Home", about: "About Us", blog: "Blog", companies: "Group Companies", contact: "Contact Us", careers: "Career Opportunities" },
    hero: { eyebrow: "Production-ready UI kits for developers", title: "Ship production-ready UI faster with", description: "Premium React, Next.js and Tailwind UI kits built to help developers ship faster, cleaner and better products.", explore: "Explore Kits", components: "View Components" },
    slogan: { text: "We are here to create new ideas together and move forward faster than ever with innovation; because we believe:", value: "simplicity is the power." },
    about: { title: "About Us", subtitle: "Simple tools, thoughtful interfaces, and production-ready code.", intro: "MinKits is a growing collection of practical UI components and kits for developers who want to build polished products without starting every interface from scratch.", items: [{ title: "Build with confidence", text: "Reusable components help teams move from idea to implementation with less repetition." }, { title: "Keep interfaces consistent", text: "Clear patterns and focused components make design systems easier to maintain." }, { title: "Ship faster", text: "Start from production-ready building blocks and spend more time on product decisions." }], cta: "Get Started" },
    features: { title: "Why MinKits?", subtitle: "Build faster, stay consistent, and focus on creating better products.", items: [{ title: "Build Faster", desc: "Skip repetitive UI work and spend more time building the features your users need." }, { title: "Production Ready", desc: "Professionally crafted components built for real-world projects and scalable applications." }, { title: "Clean & Consistent", desc: "Keep your design system unified and deliver a more polished user experience." }] },
    blog: { title: "Blog", subtitle: "Practical articles and resources for modern UI development.", readMore: "Read more", viewAll: "View all articles", posts: [{ title: "Building better interfaces with reusable components", description: "A practical look at structuring reusable UI without losing flexibility." }, { title: "A cleaner approach to Tailwind CSS", description: "Patterns that keep utility-first interfaces readable and maintainable." }, { title: "Designing production-ready React components", description: "What to consider when turning a visual idea into a reusable component." }] },
    team: { title: "Our Team", subtitle: "A small team focused on making frontend development simpler." },
    contact: { title: "Contact Us", subtitle: "Have a question or an idea? Send us a message.", name: "Name", email: "Email", message: "Message", namePlaceholder: "Your name", emailPlaceholder: "you@example.com", messagePlaceholder: "Write your message here...", legal: "By submitting, you agree to our Terms and Privacy Policy.", submit: "Submit", brandDescription: "MinKits is a growing collection of practical, production-ready UI components and kits for modern web development." },
    footer: { description: "MinKits is a growing collection of practical, production-ready UI components and kits for modern web development.", important: "Important Links", social: "Social Links", subscribe: "Subscribe for news", emailPlaceholder: "Enter your email..", button: "Subscribe", home: "Home", about: "About", portfolio: "Portfolio", contact: "Contact", faq: "FAQ", terms: "Terms & Conditions", privacy: "Privacy Policy", copyright: "© 2026 MinKits" },
    breadcrumbs: { home: "Home", about: "About Us", blog: "Blog" },
  },
  fa: {
    nav: { home: "خانه", about: "درباره ما", blog: "بلاگ", companies: "شرکت‌های گروه", contact: "ارتباط با ما", careers: "فرصت‌های شغلی" },
    hero: { eyebrow: "کیت‌های رابط کاربری آماده تولید برای توسعه‌دهندگان", title: "با سرعت بیشتری رابط کاربری آماده تولید با", description: "کیت‌ها و کامپوننت‌های حرفه‌ای React، Next.js و Tailwind برای ساخت محصولاتی سریع‌تر، تمیزتر و بهتر.", explore: "مشاهده کیت‌ها", components: "مشاهده کامپوننت‌ها" },
    slogan: { text: "اینجا هستیم تا با هم ایده‌های نو خلق کنیم و با نوآوری سریع‌تر از همیشه پیش برویم؛ چون باور داریم:", value: "سادگی، قدرت است." },
    about: { title: "درباره ما", subtitle: "ابزارهای ساده، رابط‌های فکرشده و کد آماده تولید.", intro: "MinKits مجموعه‌ای رو‌به‌رشد از کامپوننت‌ها و کیت‌های کاربردی رابط کاربری است؛ برای توسعه‌دهندگانی که می‌خواهند بدون شروع دوباره از صفر، محصولات حرفه‌ای بسازند.", items: [{ title: "با اطمینان بسازید", text: "کامپوننت‌های قابل استفاده مجدد، مسیر ایده تا پیاده‌سازی را با تکرار کمتر کوتاه می‌کنند." }, { title: "رابطی یکپارچه داشته باشید", text: "الگوهای روشن و کامپوننت‌های متمرکز، نگهداری سیستم طراحی را ساده‌تر می‌کنند." }, { title: "سریع‌تر منتشر کنید", text: "از بلوک‌های آماده تولید شروع کنید و زمان بیشتری برای تصمیم‌های محصول داشته باشید." }], cta: "شروع کنید" },
    features: { title: "چرا MinKits؟", subtitle: "سریع‌تر بسازید، یکپارچگی را حفظ کنید و روی ساخت محصول بهتر تمرکز کنید.", items: [{ title: "ساخت سریع‌تر", desc: "کارهای تکراری رابط کاربری را کنار بگذارید و زمان بیشتری برای قابلیت‌های موردنیاز کاربران صرف کنید." }, { title: "آماده تولید", desc: "کامپوننت‌هایی حرفه‌ای برای پروژه‌های واقعی و برنامه‌های قابل توسعه." }, { title: "تمیز و یکپارچه", desc: "سیستم طراحی خود را منسجم نگه دارید و تجربه‌ای حرفه‌ای‌تر ارائه دهید." }] },
    blog: { title: "بلاگ", subtitle: "مقالات و منابع کاربردی برای توسعه رابط کاربری مدرن.", readMore: "مطالعه بیشتر", viewAll: "مشاهده همه مقالات", posts: [{ title: "ساخت رابط‌های بهتر با کامپوننت‌های قابل استفاده مجدد", description: "نگاهی کاربردی به ساختاردهی کامپوننت‌های قابل استفاده مجدد بدون از دست دادن انعطاف‌پذیری." }, { title: "رویکردی تمیزتر به Tailwind CSS", description: "الگوهایی برای خوانایی و نگهداری بهتر رابط‌های ساخته‌شده با رویکرد utility-first." }, { title: "طراحی کامپوننت‌های React آماده تولید", description: "نکاتی که هنگام تبدیل یک ایده بصری به یک کامپوننت قابل استفاده مجدد باید در نظر گرفت." }] },
    team: { title: "تیم ما", subtitle: "تیمی کوچک که روی ساده‌تر کردن توسعه فرانت‌اند تمرکز دارد." },
    contact: { title: "ارتباط با ما", subtitle: "سؤال یا ایده‌ای دارید؟ برای ما پیام بفرستید.", name: "نام", email: "ایمیل", message: "پیام", namePlaceholder: "نام شما", emailPlaceholder: "you@example.com", messagePlaceholder: "پیام خود را بنویسید...", legal: "با ارسال فرم، با شرایط استفاده و سیاست حریم خصوصی موافقت می‌کنید.", submit: "ارسال", brandDescription: "MinKits مجموعه‌ای رو‌به‌رشد از کامپوننت‌ها و کیت‌های کاربردی و آماده تولید برای توسعه وب مدرن است." },
    footer: { description: "کامپوننت‌ها و کیت‌های آماده تولید برای توسعه‌دهندگان وب مدرن.", important: "لینک‌های مهم", social: "شبکه‌های اجتماعی", subscribe: "عضویت در خبرنامه", emailPlaceholder: "ایمیل خود را وارد کنید...", button: "عضویت", home: "خانه", about: "درباره ما", portfolio: "نمونه‌کارها", contact: "ارتباط با ما", faq: "سؤالات متداول", terms: "شرایط استفاده", privacy: "حریم خصوصی", copyright: "© ۲۰۲۶ MinKits" },
    breadcrumbs: { home: "خانه", about: "درباره ما", blog: "بلاگ" },
  },
} satisfies Record<Lang, unknown>;

export function getMessages(lang: Lang) { return messages[lang]; }
