import type { Metadata } from "next";
import "../styles/globals.css";
import LenisScroll from "../[lang]/components/lenis";
import Navbar from "../[lang]/components/navbar";
import Footer from "../[lang]/components/footer";
import { getDictionary, hasLocale } from "../dictionaries";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                             params,
                                         }: {
    children: React.ReactNode;
    params: Promise<{ lang: string }>;
}) {
    const { lang } = await params;

    if (!hasLocale(lang)) {
        throw new Error(`Unsupported locale: ${lang}`);
    }

    const dict = await getDictionary(lang);

    return (
        <html lang={lang} dir={lang === "fa" ? "rtl" : "ltr"}>
        <body>
        <LenisScroll />
        <NextTopLoader
            color="linear-gradient(to right, oklch(0 0 0), oklch(0 0 0))"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl
            showSpinner={false}
            speed={200}
            easing="ease"
        />
        <Navbar lang={lang} dict={dict} />
        {children}
        <Footer />
        </body>
        </html>
    );
}